---
- name: Include Distribution-specific variables (Amazon Linux)
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == 'Amazon'

- name: Include RedHat tasks
  ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Amazon'

- name: Include Amazon Linux tasks
  ansible.builtin.include_tasks: setup-Amazon.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'Amazon'

- name: Include Debian tasks
  ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Include install tasks
  ansible.builtin.include_tasks: install.yml
  when: >
    ansible_os_family == 'Debian'
    or ( ansible_os_family == 'RedHat' and ansible_distribution == 'Amazon' )
    or ( ansible_os_family == 'RedHat' and ansible_distribution != 'Amazon' and ansible_distribution_major_version | int == 7 )
