---
- name: Ensure old versions of Docker are not installed
  ansible.builtin.package:
    name:
      - docker
      - docker-engine
    state: absent
  become: true

- name: Ensure dependencies are installed
  ansible.builtin.package:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
    state: present
  become: true

- name: Import key (APT)
  ansible.builtin.get_url:
    url: "{{ docker_apt_gpg_key }}"
    dest: "{{ docker_apt_keyring }}"
    mode: '0644'
    force: true
  become: true

- name: Disable Docker repository not using keyring (APT)
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ docker_apt_arch }}] {{ docker_repo_url }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
    filename: docker
    state: absent
  become: true

- name: Enable Docker repository (APT)
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repository }}"
    filename: docker
    state: present
    update_cache: true
  become: true
