---
- name: Ensure old versions of Docker are not installed
  package:
    name:
      - docker
      - docker-engine
    state: absent

- name: Ensure dependencies are installed
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
    state: present

- name: Import key (APT)
  apt_key:
    url: "{{ docker_apt_gpg_key }}"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key

- name: Enable Docker repository (APT)
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    filename: docker
    state: present
    update_cache: true
