---
- name: Ensure old versions of Docker are not installed
  package:
    name:
      - docker
      - docker-common
      - docker-engine
    state: absent
  become: true

- name: Import key (Yum)
  rpm_key:
    key: "{{ docker_yum_gpg_key }}"
    state: present
  become: true

- name: Add Docker repository
  get_url:
    url: "{{ docker_yum_repo_url }}"
    dest: '/etc/yum.repos.d/{{ docker_package }}.repo'
    owner: root
    group: root
    mode: 0644
  become: true
