---
- name: Enable docker from amazon-linux-extras
  ansible.builtin.command: amazon-linux-extras enable docker
  register: result
  failed_when: result.rc != 0
  become: true
  changed_when: false
  when: ansible_distribution_major_version|int < 2023

- name: Install docker
  ansible.builtin.package:
    name: "{{ docker_package }}"
    state: present
  become: true
  when: ansible_distribution_major_version|int >= 2023
