---
- name: Converge
  hosts: all
  tasks:
    - name: "Include docker"
      include_role:
        name: "docker"
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
