---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos8
    image: geerlingguy/docker-centos8-ansible:latest
    command: /usr/sbin/init
    privileged: True
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    env:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy}"
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
