---
- name: Prepare
  hosts: all
  tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
    - name: Create /etc/docker folder
      file:
        state: directory
        path: /etc/docker
    - name: Set storage-driver to vfs
      copy:
        content: |
          {
            "storage-driver": "vfs"
          }
        dest: /etc/docker/daemon.json
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
  become: true
